apiVersion: apps/v1
kind: Deployment
metadata:
  name: galaga-backend
  namespace: galaga
spec:
  replicas: 2
  selector:
    matchLabels:
      app: galaga-backend
  template:
    metadata:
      labels:
        app: galaga-backend
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
        - name: backend
          image: 851957594139.dkr.ecr.ap-northeast-2.amazonaws.com/toy/k8s/back:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4000
          env:
            - name: PORT
              value: "4000"
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: galaga-db-secret
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: galaga-db-secret
                  key: DB_PORT
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: galaga-db-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: galaga-db-secret
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: galaga-db-secret
                  key: DB_NAME
          readinessProbe:
            httpGet:
              path: /health
              port: 4000
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 4000
            initialDelaySeconds: 20
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: galaga-backend
  namespace: galaga
spec:
  selector:
    app: galaga-backend
  ports:
    - port: 4000
      targetPort: 4000
