apiVersion: apps/v1
kind: Deployment
metadata:
  name: galaga-frontend
  namespace: galaga
spec:
  replicas: 2
  selector:
    matchLabels:
      app: galaga-frontend
  template:
    metadata:
      labels:
        app: galaga-frontend
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
        - name: frontend
          image: 851957594139.dkr.ecr.ap-northeast-2.amazonaws.com/toy/k8s/front:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: galaga-frontend
  namespace: galaga
spec:
  selector:
    app: galaga-frontend
  ports:
    - port: 80
      targetPort: 80
